### ISSUE TITLE
snmp_community - TypeError: string indices must be integers

### ISSUE THREAD

**Issue by refriedjello** [jedelman8/nxos-ansible#83]
Running task to set SNMP community string using module nxos_snmp_community I get an error, but the configuration is pushed out correctly to the switch.

Here is task I am running:

```
- name: Configure SNMP community
  nxos_snmp_community: community='notpublic' group=network-operator host={{ inventory_hostname }} state=present
```

Here is full error:

> An exception occurred during task execution. The full traceback is:
> Traceback (most recent call last):
>   File "/home/admin/.ansible/tmp/ansible-tmp-1458244641.41-123832913593499/nxos_snmp_community", line 2179, in <module>
>     main()
>   File "/home/admin/.ansible/tmp/ansible-tmp-1458244641.41-123832913593499/nxos_snmp_community", line 175, in main
>     existing = snmp.get_snmp_community(device, community)
>   File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/utils/snmp.py", line 62, in get_snmp_community
>     key = str(each['community_name'])
> TypeError: string indices must be integers

But the configuration shows up fine on the switch:

> n9372px-01# sh run | i "snmp-server community"
> snmp-server community notpublic group network-operator

**Comment by refriedjello** [comment]
Here is the full playbook I am running:

```

---

- name: Configure Nexus 9300 switches
  hosts: spine
  connection: local
  gather_facts: no

  tasks:

    - name: Configure SNMP community
      nxos_snmp_community: community=notpublic group=network-operator host={{ inventory_hostname }} state=present
```

Am I specifying the string wrong somehow? I tried a few different methods of quoting it.

Thanks,
