### ISSUE TITLE
Looping with list of IP's not working 

### ISSUE THREAD

**Issue by geepees2015** [jedelman8/nxos-ansible#87]
Hi
I was trying to put 2 ntp server's with the item list as follows:

```
- nxos_ntp: host={{ inventory_hostname }} server={{ item }} source_int=loopback0 username=admin password="xxxxx" protocol=https state=present
   with_items:
    - "10.110.80.1"
    - "10.110.90.5"
```

I am seeing the following error when I run the above which is:

ERROR! Syntax Error while loading YAML.

The error appears to have been in '/usr/share/ansible/samples/test3snmp-interface.yml': line 29, column 18, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

```
- nxos_ntp: host={{ inventory_hostname }} server={{ item }} source_int=loopback0 username=admin password="xxxxx" protocol=https state=present
   with_items:
             ^ here
```

Any reason on why it breaks?

Thanks ?

**Comment by jedelman8** [comment]
The `with_items` needs to be directly under the `nxos_ntp` - you have an extra space in there.

**Comment by geepees2015** [comment]
I had fixed that yesterday and still see same error. I am assuming that the n from 'nxos' and w from 'with_tems' need to be aligned. Is that correct ?:

```
---

- name: interface testing
  hosts: leaf
  connection: local
  gather_facts: no


  tasks:
    - nxos_ntp: server= '{{ item }}' host={{ inventory_hostname }} source_int=loopback0 username=admin  password="xxxx" protocol=https state=present
      with_items:
        - 10.110.80.1
        - 10.110.90.5       
```

**Comment by geepees2015** [comment]
Jason,
Let me know if you want to try anything else.

Thanks !

**Comment by jedelman8** [comment]
You also have a space after the `=` after `server`.  You also have quotes around "item"...remove that..

It should be `server={{ item }}`

**Comment by geepees2015** [comment]
It still does not work and gives error and the yaml looks as follows:

```
---

- name: interface testing
  hosts: leaf
  connection: local
  gather_facts: no


  tasks:
    - nxos_ntp: server={{ item }} host={{ inventory_hostname }} source_int=loopback0 username=admin password=“xxxx” protocol=https state=present
      with_items:
        - 10.110.80.1
        - 10.110.90.5
```

Thanks !

**Comment by jedelman8** [comment]
Please start using back ticks in your code blocks and YAML files and please show the full error.

**Comment by geepees2015** [comment]
```Using /etc/ansible/ansible.cfg as config file
ERROR! unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

The error appears to have been in '/usr/share/ansible/samples/test4-interface.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - nxos_ntp: server={{ item }} host={{ inventory_hostname }} source_int=loopback0 username=admin password="G3ops_sanr@mon2015!" protocol=https state=present
      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

```
with_items:
  - {{ foo }}
```

Should be written as:

```
with_items:
  - "{{ foo }}"
```

The error appears to have been in '/usr/share/ansible/samples/test4-interface.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - nxos_ntp: server={{ item }} host={{ inventory_hostname }} source_int=loopback0 username=admin password="G3ops_sanr@mon2015!" protocol=https state=present
      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

```
with_items:
  - {{ foo }}
```

Should be written as:

```
with_items:
  - "{{ foo }}"
```

```
```

**Comment by jedelman8** [comment]
Okay, I believe Cisco changed their API and could be why a few of these modules aren't working.  This may be one of them (ugh!). Sorry about this.

**Comment by geepees2015** [comment]
any workaround will be appreciated.

**Comment by refriedjello** [comment]
As a work-around you could define each in their own tasks. This is working for me. Also lets me define the preferred NTP server.

```
    - name: Define primary trusted NTP time source
      nxos_ntp: server={{ ntp1 }} prefer=enabled vrf_name=management host={{ inventory_hostname }} state=present

    - name: Define secondary trusted NTP time source
      nxos_ntp: server={{ ntp2 }} prefer=disabled vrf_name=management host={{ inventory_hostname }} state=present
```

**Comment by refriedjello** [comment]
Also just noticed, I don't remember seeing the "item" array being specified that way in any examples. I just tested this and it works:

```
---

- name: Configure Nexus 9300 switches
  hosts: spine
  connection: local
  gather_facts: no

  tasks:

    - name: Define primary trusted NTP time source
      nxos_ntp: server={{ item.ntp }} prefer=enabled vrf_name=management host={{ inventory_hostname }} state=present
      with_items:
        - { ntp: 1.1.1.1 }
        - { ntp: 2.2.2.2 }
```
