### ISSUE TITLE
Creating users on nexus 

### ISSUE THREAD

**Issue by geepees2015** [jedelman8/nxos-ansible#88]
Hi.
Do you have any playbooks for creating users with admin or read access ?

Thanks !

**Comment by geepees2015** [comment]
Is this in the works as I wanted to deploy user's with different roles on all devices ?

Thanks !

**Comment by jedelman8** [comment]
There is not a nxos_user module planned at this point, but now we know there is a need.

Your best bet is nxos_command:

```
- nxos_command:
    host: "{{ inventory_hostname }}"
    type: config
    username: xxxx
    password: xxxx
    command_list:
      - username xxxx password xxx
      - command 2
```
